In [4]:
import numpy as np
from proj1_helpers import *

In [8]:
DATA_DIR = "../../../MLData2018/"

In [9]:
data = load_csv_data(DATA_DIR+"train.csv")

In [10]:
data

(array([ 1., -1., -1., ...,  1., -1., -1.]),
 array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
        [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
        [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
        ..., 
        [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
        [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
        [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]]),
 array([100000, 100001, 100002, ..., 349997, 349998, 349999]))

In [81]:
dx = data[1]
dx

array([[  1.38470000e+02,   5.16550000e+01,   9.78270000e+01, ...,
          1.24000000e+00,  -2.47500000e+00,   1.13497000e+02],
       [  1.60937000e+02,   6.87680000e+01,   1.03235000e+02, ...,
         -1.18452642e-02,  -1.58228913e-03,   4.62260000e+01],
       [  1.21858528e+02,   1.62172000e+02,   1.25953000e+02, ...,
         -1.18452642e-02,  -1.58228913e-03,   4.42510000e+01],
       ..., 
       [  1.05457000e+02,   6.05260000e+01,   7.58390000e+01, ...,
         -1.18452642e-02,  -1.58228913e-03,   4.19920000e+01],
       [  9.49510000e+01,   1.93620000e+01,   6.88120000e+01, ...,
         -1.18452642e-02,  -1.58228913e-03,   0.00000000e+00],
       [  1.21858528e+02,   7.27560000e+01,   7.08310000e+01, ...,
         -1.18452642e-02,  -1.58228913e-03,   0.00000000e+00]])

In [59]:
def column_replace_invalid_by_mean(col):
    mean = np.mean(col[col != -999])
    col[col == -999] = mean
    return col

In [82]:
def fill_unknown_with_column_mean(dx):
    d = dx.transpose()
    for i in range(len(d)):
        col = d[i]
        d[i] = column_replace_invalid_by_mean(col)
    return d.transpose()
        

In [85]:
dx = fill_unknown_with_column_mean(dx)

In [86]:
def standardize(dx):
    d = dx.transpose()
    for i in range(len(d)):
        mean = d[i].mean()
        std = d[i].std()
        d[i] = (d[i] - mean) / std
    return d.transpose()

In [95]:
dx = standardize(dx)